# Generated by Django 2.0.7 on 2018-07-28 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bil',
            new_name='bio',
        ),
    ]
